import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
function harness(){const elements=new Map(),locations=[],metadata=[];const el=id=>{if(!elements.has(id))elements.set(id,{value:'',hidden:false,disabled:false,files:[],children:[],textContent:'',click(){},removeAttribute(){},replaceChildren(){this.children=[]},append(v){this.children.push(v)},reset(){}});return elements.get(id)};const context=vm.createContext({document:{getElementById:el,createElement:()=>({append(){}})},navigator:{geolocation:{getCurrentPosition(ok,fail){locations.push({ok,fail})}}},PhotoMetadata:{fromFile:()=>new Promise(resolve=>metadata.push(resolve))},URL:{createObjectURL:()=> 'blob:test',revokeObjectURL(){}},fetch:async()=>({ok:true,status:200,json:async()=>({items:[]})}),Date,Number,Math,FormData,crypto:{randomUUID:()=> '12345678-1234-1234-1234-123456789abc'}});vm.runInContext(readFileSync(new URL('../dist/collect.js',import.meta.url),'utf8'),context);return {el,locations,metadata,run:s=>vm.runInContext(s,context),context}}
const file="{name:'test.jpg',size:100,type:'image/jpeg',lastModified:Date.now()}";
test('upload with no metadata never uses current date or GPS',async()=>{const h=harness();const p=h.run(`select(${file},'library')`);h.metadata[0]({});await p;assert.equal(h.el('time').value,'');assert.equal(h.locations.length,0);assert.equal(h.el('save').disabled,false)});
test('camera picker also requires explicit fresh capture confirmation',async()=>{const h=harness();const p=h.run(`select(${file},'camera')`);h.metadata[0]({});await p;assert.equal(h.el('time').value,'');assert.equal(h.locations.length,0);h.el('fresh').checked=true;h.el('fresh').onchange();assert.ok(h.el('time').value);assert.equal(h.locations.length,1);h.locations[0].fail();assert.equal(h.el('save').disabled,false)});
test('replacement and manual edits defeat delayed metadata',async()=>{const h=harness();const a=h.run(`select(${file},'library')`),b=h.run(`select(${file},'library')`);h.metadata[1]({});await b;h.metadata[0]({localTime:'2020-01-01T12:30:00',coordinates:{latitude:1,longitude:2}});await a;assert.equal(h.el('time').value,'');assert.equal(h.el('latitude').value,'');const c=h.run(`select(${file},'library')`);h.el('time').value='2022-01-01T12:00';h.el('time').oninput();h.el('clear').onclick();h.metadata[2]({localTime:'2020-01-01T12:30:00',coordinates:{latitude:1,longitude:2}});await c;assert.equal(h.el('time').value,'2022-01-01T12:00');assert.equal(h.el('latitude').value,'')});
test('clear, replacement and newer location request defeat stale location',async()=>{const h=harness();const p=h.run(`select(${file},'library')`);h.metadata[0]({});await p;const position={coords:{latitude:22,longitude:113,accuracy:5},timestamp:Date.now()};h.el('locate').onclick();h.el('clear').onclick();h.locations[0].ok(position);assert.equal(h.el('latitude').value,'');h.el('locate').onclick();h.el('locate').onclick();h.locations[1].ok(position);assert.equal(h.el('latitude').value,'');h.locations[2].ok(position);assert.equal(h.el('latitude').value,22);const p2=h.run(`select(${file},'library')`);h.locations[2].ok(position);h.metadata[1]({});await p2;assert.equal(h.el('latitude').value,'')});
test('save waits for metadata, failed save preserves photo, and late GPS cannot mutate retry',async()=>{const h=harness();h.context.photo=new File(['photo'],'flower.jpg',{type:'image/jpeg'});const p=h.run("select(photo,'library')");let posts=0;h.context.fetch=async()=>{posts++;throw new Error('Offline')};await h.el('form').onsubmit({preventDefault(){}});assert.equal(posts,0);h.metadata[0]({});await p;h.el('locate').onclick();await h.el('form').onsubmit({preventDefault(){}});assert.equal(posts,1);assert.equal(h.run('selectedFile'),h.context.photo);assert.equal(h.el('save').disabled,false);h.locations[0].ok({coords:{latitude:22,longitude:113,accuracy:5},timestamp:Date.now()});assert.equal(h.el('latitude').value,'');assert.match(h.el('status').textContent,/retry/)});
