import test from 'node:test';import assert from 'node:assert/strict';import worker from '../dist/server/index.js';
const id='8000000000000-12345678-1234-1234-1234-123456789abc';
function bucket(){const entries=new Map();return {entries,async put(key,body,opts){entries.set(key,{body,...opts})},async head(key){return entries.get(key)},async get(key){return entries.get(key)},async list({prefix}){return {objects:[...entries].filter(([key])=>key.startsWith(prefix)).map(([key,o])=>({key,...o})),truncated:false}}}}
function upload(user='alice',origin='https://test.local',image=[255,216,255,224]){const data=new FormData();data.append('photo',new File([new Uint8Array(image)],'flower.jpg',{type:'image/jpeg'}));data.append('metadata',JSON.stringify({id,observedAt:'2026-09-19T09:00:00+08:00',notes:'Unknown pink flower',location:null}));return new Request('https://test.local/api/observations',{method:'POST',headers:{'oai-authenticated-user-id':user,Origin:origin},body:data})}
test('save, repeat safely, reload and isolate private records',async()=>{const env={BUCKET:bucket()};assert.equal((await worker.fetch(upload(),env)).status,201);assert.equal((await worker.fetch(upload(),env)).status,200);assert.equal(env.BUCKET.entries.size,1);const list=await worker.fetch(new Request('https://test.local/api/observations',{headers:{'oai-authenticated-user-id':'alice'}}),env);const data=await list.json();assert.equal(data.items[0].status,'unidentified');assert.equal(data.items[0].location,null);assert.equal(data.items[0].observedAt,'2026-09-19T01:00:00.000Z');const other=await worker.fetch(new Request('https://test.local/api/observations/'+id+'/photo',{headers:{'oai-authenticated-user-id':'bob'}}),env);assert.equal(other.status,404)});
test('reject unauthenticated, cross-origin and fake image requests',async()=>{const env={BUCKET:bucket()};assert.equal((await worker.fetch(new Request('https://test.local/api/observations'),env)).status,401);assert.equal((await worker.fetch(upload('alice','https://other.local'),env)).status,403);assert.equal((await worker.fetch(upload('alice',undefined,[1,2,3]),env)).status,400);assert.equal(env.BUCKET.entries.size,0)});
test('unavailable storage reports failure rather than saved',async()=>{assert.equal((await worker.fetch(upload(),{})).status,503)});
test('character map and shared morphology assets are served',async()=>{for(const path of ['/characters','/characters/','/characters.js','/characters.css','/image-analysis.js','/morphology.js']){const res=await worker.fetch(new Request('https://test.local'+path),{});assert.equal(res.status,200,path);assert.ok((await res.text()).length>100);}});
async function uploadDetails(details){const original=upload();const form=await original.formData();form.set('metadata',JSON.stringify({id,notes:'',location:null,...details}));return new Request(original.url,{method:'POST',headers:{Origin:'https://test.local','oai-authenticated-user-id':'alice'},body:form})}
test('photo-only saves keep observation unknown independently from upload time',async()=>{const env={BUCKET:bucket()};const response=await worker.fetch(await uploadDetails({observedAt:null}),env);assert.equal(response.status,201);const record=await response.json();assert.equal(record.observedAt,null);assert.equal(record.observedAtSource,'unknown');assert.ok(record.uploadedAt)});
test('timezone-free photo time and GPS provenance round trip without fabricated accuracy',async()=>{const env={BUCKET:bucket()};const response=await worker.fetch(await uploadDetails({observedAt:null,observedLocalTime:'2020-02-29T12:30',observedAtSource:'photo_exif',location:{latitude:22.2,longitude:113.5,source:'photo_exif'}}),env);assert.equal(response.status,201);const record=await response.json();assert.equal(record.observedAt,null);assert.equal(record.observedLocalTime,'2020-02-29T12:30');assert.equal(record.observedAtSource,'photo_exif');assert.equal(record.location.accuracy,null);assert.equal(record.location.capturedAt,null)});
test('invalid optional metadata is rejected; collection assets are routed',async()=>{for(const details of [{observedLocalTime:'2021-02-29T12:30'},{location:{latitude:91,longitude:1,source:'manual'}},{observedAt:'broken'}])assert.equal((await worker.fetch(await uploadDetails(details),{BUCKET:bucket()})).status,400);for(const path of ['/collect','/photo-metadata.js','/collect-flow.css'])assert.equal((await worker.fetch(new Request('https://test.local'+path),{})).status,200)});
