const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context=vm.createContext({});vm.runInContext(fs.readFileSync('dist/morphology.js','utf8')+'\n'+fs.readFileSync('dist/engine-profiles.js','utf8')+'\n'+fs.readFileSync('dist/engine-v3.js','utf8')+'\nthis.engine=FlowerEngine;this.profiles=ENGINE_PROFILES;',context);const {engine,profiles}=context;
function fixture(center=true){const w=80,data=new Uint8ClampedArray(w*w*4);for(let y=0;y<w;y++)for(let x=0;x<w;x++){const d=Math.hypot(x-40,y-40),yellow=center?d<8:d>16;data.set(d<22?(yellow?[255,220,0,255]:[245,245,245,255]):[20,100,30,255],(y*w+x)*4)}return data;}
test('center evidence measures position, not total yellow',()=>{const a=engine.extract(fixture(true),80,80).features,b=engine.extract(fixture(false),80,80).features;assert.ok(a.center_yellow>b.center_yellow);assert.ok(a.outer_yellow<b.outer_yellow)});
test('empty and uniform backgrounds cannot be accepted',()=>{for(const rgb of [[0,0,0],[245,245,245],[20,100,30]]){const data=new Uint8ClampedArray(80*80*4);for(let p=0;p<6400;p++)data.set([...rgb,255],p*4);const out=engine.analyze(data,80,80,profiles);assert.equal(out.decision.accepted,false);assert.equal(out.quality.usable,false)}});
test('all valid pixels belong to exactly one region',()=>{const out=engine.extract(fixture(),80,80);for(let p=0;p<6400;p++)assert.equal(out.masks.flower[p]+out.masks.leaf[p]+out.masks.context[p],1)});
test('rule data changes scores and missing measurements abstain',()=>{const p=[{id:'a',rules:{colour:[['yellow',.8,1,1]]}},{id:'b',rules:{colour:[['yellow',0,.1,1]]}}];assert.equal(engine.rank({yellow:.9},p)[0].id,'a');assert.equal(engine.rank({yellow:.01},p)[0].id,'b');assert.equal(engine.rank({},p)[0].observed_groups,0)});
test('catalog includes six Macau groups and seed-head hypothesis',()=>{for(const id of ['hibiscus','ixora','lantana','plumeria','bougainvillea','bidens'])assert.ok(profiles.some(p=>p.id===id));assert.ok(profiles.some(p=>p.stage==='mature_seed_head'));assert.equal(engine.analyze(fixture(),80,80,profiles).decision.accepted,false)});
test('crop-level structure expectations are sourced, scoped and inspect-only',()=>{for(const id of ['hibiscus','waterlily','plumeria','ixora','lantana','sunflower','daisy','bidens']){const profile=profiles.find(row=>row.id===id&&row.stage==='flowering'),expectation=profile.visibleStructureExpectation;assert.ok(expectation,id);assert.equal(expectation.observationScope,'selected_crop');assert.equal(expectation.rankingMode,'inspect_only');assert.match(expectation.sourceRecord,/^botanical-knowledge:/);assert.ok(expectation.scope);}const dandelion=profiles.find(row=>row.id==='dandelion'&&row.stage==='flowering'),bougainvillea=profiles.find(row=>row.id==='bougainvillea');assert.equal(dandelion.visibleStructureExpectation.status,'unsupported_observer_class');assert.equal(bougainvillea.visibleStructureExpectation.status,'unsupported_observer_class');});
test('guided extraction records a contained seed and structural uncertainty',()=>{const out=engine.extract(fixture(),80,80,{seed:{x:.5,y:.5}});assert.equal(out.quality.seeded,true);assert.equal(out.quality.seed_contained,true);for(const key of ['circularity','solidity','symmetry','visible_tips_low','visible_tips_high','tip_stability','centre_contrast'])assert.ok(Number.isFinite(out.features[key]),key);assert.ok(out.features.visible_tips_high>=out.features.visible_tips_low);assert.equal(typeof out.features.structural_class,'string')});
test('a tap outside detectable flower pixels fails explicitly',()=>{const out=engine.extract(fixture(),80,80,{seed:{x:0,y:0}});assert.equal(out.quality.usable,false);assert.equal(out.quality.seed_contained,false);assert.match(out.quality.issues.join(' '),/Tap did not land/)});
test('analysis stays uncalibrated and requests actionable follow-up',()=>{const out=engine.analyze(fixture(),80,80,profiles,{seed:{x:.5,y:.5}});assert.equal(out.decision.accepted,false);assert.ok(out.decision.follow_up.length>20);assert.equal(out.engine_version,'0.15.0')});

function shapeMask(kind,size=160){const m=new Uint8Array(size*size);for(let y=0;y<size;y++)for(let x=0;x<size;x++){const dx=x-size/2,dy=y-size/2,a=Math.atan2(dy,dx),r=kind==='circle'?size*.3:size*(.22+.09*Math.cos(5*a));if(Math.hypot(dx,dy)<r)m[y*size+x]=1;}return m;}
test('silhouette distinguishes rounded and lobed shapes without inventing petals',()=>{const a=engine.describeOutline(shapeMask('circle'),160,160,{usable:true}),b=engine.describeOutline(shapeMask('lobed'),160,160,{usable:true});assert.equal(a.outline.value,'rounded');assert.equal(b.outline.value,'lobed_or_elongated');assert.equal(b.petal_count,null);assert.equal(b.petal_tip_shape,'unknown');});
test('unusable and clipped outlines abstain',()=>{assert.equal(engine.describeOutline(shapeMask('circle'),160,160,{usable:false}).outline.value,'unknown');const m=shapeMask('circle');m[0]=1;assert.equal(engine.describeOutline(m,160,160,{usable:true}).tips.value,'unknown');});
test('categorical shape changes rank without colour changes; unknowns abstain',()=>{const ps=[{id:'round',rules:{shape:[['fill',0,1,1]]},morphology:{tips:['rounded']}},{id:'point',rules:{shape:[['fill',0,1,1]]},morphology:{tips:['pointed']}}];for(const [value,id] of [['rounded','round'],['pointed','point']]){const r=engine.rank({fill:.5,morphology:{tips:{value}}},ps);assert.equal(r[0].id,id);assert.ok(r[1].evidence.some(e=>e.contradiction));}const r=engine.rank({fill:.5,morphology:{tips:{value:'unknown'}}},ps);assert.equal(r[0].score,r[1].score);});
test('wide and narrow synthetic apexes produce different tip observations',()=>{for(const [power,expected] of [[.3,'rounded'],[3,'pointed']]){const n=200,m=new Uint8Array(n*n);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const a=Math.atan2(y-100,x-100),r=40+30*((1+Math.cos(5*a))/2)**power;if(Math.hypot(x-100,y-100)<r)m[y*n+x]=1;}assert.equal(engine.describeOutline(m,n,n,{usable:true}).tips.value,expected);}});

function rayHead(mode='head'){const n=128,d=new Uint8ClampedArray(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const r=Math.hypot(x-64,y-64),a=Math.atan2(y-64,x-64);let rgb=[25,90,180,255];if(r<36+6*Math.cos(16*a))rgb=[250,205,25,255];if(mode==='head'&&r<21)rgb=[65,75,35,255];if(mode==='solid'){}if(mode==='fragment')rgb=x>60&&x<65&&y>60&&y<65?[250,205,25,255]:[25,90,180,255];d.set(rgb,(y*n+x)*4);}return d;}
test('automatic head includes contrasting centre and separate outer rays',()=>{const o=engine.analyze(rayHead(),128,128,profiles);assert.equal(o.head_structure.status,'centre_surrounded_by_yellow_outer_region');assert.ok(o.masks.centre[64*128+64]);assert.ok(o.masks.flower[64*128+64]);assert.ok(!o.masks.rays[64*128+64]);assert.equal(o.candidates[0].id,'sunflower');assert.equal(o.decision.accepted,false);});
test('yellow solid objects and fragments do not establish sunflower structure',()=>{for(const mode of ['solid','fragment']){const o=engine.analyze(rayHead(mode),128,128,profiles);assert.equal(o.head_structure.status,'unknown');const candidate=o.candidates.find(c=>c.id==='sunflower');assert.ok(candidate);assert.equal(candidate.evidence_status,'incomplete_structure');assert.ok(candidate.coverage<1);assert.equal(o.decision.accepted,false);}});
test('attributed sunflower development reference retains centre and ranks sunflower',()=>{const o=engine.analyze(fs.readFileSync('tests/head-reference/sunflower-256x190.rgba'),256,190,profiles);assert.equal(o.head_structure.status,'centre_surrounded_by_yellow_outer_region');assert.equal(o.candidates[0].id,'sunflower');assert.equal(o.decision.accepted,false);assert.ok(o.masks.centre.reduce((a,b)=>a+b,0)>1000);for(let p=0;p<o.masks.flower.length;p++){if(o.masks.centre[p]||o.masks.rays[p])assert.equal(o.masks.flower[p],1);assert.ok(!(o.masks.centre[p]&&o.masks.rays[p]));}});
test('automatic adapter renders without feedback controls',()=>{const els={},get=id=>els[id]??={style:{},addEventListener(){throw Error('No region interaction allowed')}};const c=vm.createContext({window:{},document:{querySelector:get},$:get,preview:get('preview')});vm.runInContext(fs.readFileSync('dist/engine-ui-guided.js','utf8'),c);c.out=engine.analyze(rayHead(),128,128,profiles);vm.runInContext('render(out)',c);assert.equal(els.runStatus.textContent,'AUTOMATIC · EXPERIMENTAL');assert.ok(els.featureRows.innerHTML.includes('PETAL SHAPE'));for(const f of ['dist/index.html','dist/engine-ui-guided.js'])assert.ok(!/tapInstruction|seedMarker|tap elsewhere|TAP REQUIRED/.test(fs.readFileSync(f,'utf8')));});
function petalFixture(count){const n=160,m=new Uint8Array(n*n);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const a=Math.atan2(y-80,x-80),r=16+45*((1+Math.cos(count*a))/2);if(Math.hypot(x-80,y-80)<r)m[y*n+x]=1;}return m;}
test('separated petal-region hypotheses count three through six with numbered contained regions',()=>{for(const n of [3,4,5,6]){const mask=petalFixture(n),o=engine.petalRegions(mask,160,160,{usable:true});assert.equal(o.visible_region_count,n);assert.equal(o.regions.length,n);assert.equal(o.category,String(n));for(let p=0;p<mask.length;p++)if(o.labels[p])assert.equal(mask[p],1);assert.equal(new Set(Array.from(o.labels).filter(Boolean)).size,n);}});
test('merged, clipped and unreliable petal regions remain unresolved',()=>{for(const [m,q] of [[shapeMask('circle'),true],[petalFixture(5),false]])assert.equal(engine.petalRegions(m,160,160,{usable:q}).visible_region_count,null);const m=petalFixture(5);m[0]=1;assert.equal(engine.petalRegions(m,160,160,{usable:true}).category,'unresolved');});
test('sunflower photo does not receive an invented botanical petal count',()=>{const o=engine.analyze(fs.readFileSync('tests/head-reference/sunflower-256x190.rgba'),256,190,profiles);assert.equal(o.petals.unit,'petal_or_ray_region_candidate');assert.ok(!('petal_count' in o.petals));console.log('Sunflower visible-region result:',o.petals.category,o.petals.reason);});
function edgeFixture(mode){const n=160,mask=new Uint8Array(n*n),data=new Uint8Array(n*n*4);for(let y=0;y<n;y++)for(let x=0;x<n;x++){const a=(Math.atan2(y-80,x-80)+Math.PI*2)%(Math.PI*2),r=Math.hypot(x-80,y-80);mask[y*n+x]=r<60;let v=200;if(mode==='sectors')v=[245,140,230,130,220][Math.floor(a/(Math.PI*2)*5)];if(mode==='short'&&r>35&&r<42)v=[245,140,230,130,220][Math.floor(a/(Math.PI*2)*5)];data.set([v,v*.55,v*.7,255],(y*n+x)*4);}return{data,mask,n};}
test('internal edges separate five touching colour regions without outline gaps',()=>{const {data,mask,n}=edgeFixture('sectors'),o=engine.edgePetals(data,mask,n,n,{usable:true});assert.equal(o.visible_region_count,5);assert.equal(o.method,'internal_edges_and_region_stability');for(let p=0;p<mask.length;p++)if(o.boundary[p]||o.labels[p])assert.equal(mask[p],1);});
test('smooth regions and short internal marks do not produce an edge count',()=>{for(const mode of ['smooth','short']){const {data,mask,n}=edgeFixture(mode),o=engine.edgePetals(data,mask,n,n,{usable:true});assert.equal(o.visible_region_count,null);assert.equal(o.edge_diagnostics.used_for_count,false);}});

test('botanical observations retain region units and unknown anatomy',()=>{const o=engine.analyze(rayHead(),128,128,profiles).observations;assert.equal(o.petalTip.value,null);assert.equal(o.arrangement.value,null);assert.equal(o.leafSupport.value,null);assert.equal(o.centre.status,'region_candidate');assert.ok(o.centre.evidence.length);});
test('morphology proposals are inspectable but never substitute for observed petals',()=>{const {data,mask,n}=edgeFixture('sectors');const out=context.FlowerMorphology;const m=engine.analyze(rayHead(),128,128,profiles);assert.equal(m.morphology.status,'exploratory');assert.equal(m.decision.accepted,false);for(const method of m.morphology.methods){assert.equal(method.status,'exploratory');assert.equal(method.count,method.regions.length);for(let p=0;p<method.labels.length;p++)if(method.labels[p])assert.equal(m.masks.flower[p],1);}});
test('colour regions with no texture remain one exploratory region, never anatomical count',()=>{vm.runInContext('this.morph=FlowerMorphology',context);const {data,mask,n}=edgeFixture('smooth'),m=context.morph.run(data,mask,n,n);assert.equal(m.methods[0].count,1);assert.equal(m.status,'exploratory');assert.equal(m.methods.length,1);});
test('morphology can partition a connected image using internal colour boundaries',()=>{const {data,mask,n}=edgeFixture('sectors');vm.runInContext('this.morph=FlowerMorphology',context);const m=context.morph.run(data,mask,n,n);assert.ok(m.methods.some(x=>x.count>1));assert.ok(m.methods.some(x=>x.name==='seeded_gradient_flood'));});

test('missing required evidence retains candidates with reduced coverage, never a free perfect match',()=>{
 const ps=[{id:'head',requiredFeatures:['disc'],rules:{colour:[['yellow',.4,1,1]],centre:[['disc',.2,.6,1]]}}];
 const partial=engine.rank({yellow:.8},ps)[0],full=engine.rank({yellow:.8,disc:.4},ps)[0],conflict=engine.rank({yellow:.8,disc:1},ps)[0];
 assert.equal(partial.compatibility,1);assert.equal(partial.coverage,.5);assert.equal(partial.score,.5);assert.equal(partial.missing_required[0],'disc');assert.equal(partial.evidence_status,'incomplete_structure');assert.ok(full.score>partial.score);assert.ok(conflict.evidence.some(e=>e.contradiction));assert.equal(engine.rank({},ps)[0].score,0);
});
test('observed head layout changes ranking through the character bridge; exploratory counts cannot',()=>{
 const ps=[{id:'rays',headLayout:'disc_with_outer_rays',rules:{shape:[['fill',0,1,1]]}},{id:'all',headLayout:'all_rays',rules:{shape:[['fill',0,1,1]]}}];
 const f={fill:.5};const a=engine.rank(f,ps),b=engine.rank(f,ps,{head_layout:'disc_with_outer_rays'});
 assert.equal(a[0].score,a[1].score);assert.ok(b[0].score>b[1].score);assert.equal(b[0].id,'rays');
 const ignored=engine.rank({...f,exploratory_count:6},ps);assert.equal(ignored[0].score,a[0].score);
 const blank=engine.analyze(new Uint8Array(128*128*4),128,128,profiles);assert.ok(blank.candidates.every(c=>c.score===0&&c.coverage===0));
});
test('spatial head can retain a bright green centre without requiring a dark disc',()=>{
 const d=rayHead();for(let y=0;y<128;y++)for(let x=0;x<128;x++)if(Math.hypot(x-64,y-64)<21)d.set([130,240,120,255],(y*128+x)*4);
 const o=engine.analyze(d,128,128,profiles);assert.equal(o.head_structure.method,'spatial_colour_transition');assert.equal(o.candidates[0].id,'sunflower');assert.ok(o.masks.centre[64*128+64]);assert.ok(o.masks.rays.reduce((a,b)=>a+b,0)>80);assert.equal(o.decision.accepted,false);
});
test('user screenshot regression retains sunflower and excludes lower leaf/stem from flower mask',()=>{
 const o=engine.analyze(fs.readFileSync('tests/user-reference/sunflower-screen-255x300.rgba'),255,300,profiles);
 assert.equal(o.head_structure.method,'spatial_colour_transition');assert.equal(o.candidates[0].id,'sunflower');assert.equal(o.candidates[0].missing_required.length,0);assert.equal(o.decision.accepted,false);
 for(let p=255*225;p<255*300;p++)assert.equal(o.masks.flower[p],0);
 assert.equal(o.petals.visible_region_count,null);
});
