const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context=vm.createContext({});vm.runInContext(fs.readFileSync('dist/engine-profiles.js','utf8')+'\n'+fs.readFileSync('dist/engine-v3.js','utf8')+'\nthis.engine=FlowerEngine;this.profiles=ENGINE_PROFILES;',context);const {engine,profiles}=context;
function fixture(center=true){const w=80,data=new Uint8ClampedArray(w*w*4);for(let y=0;y<w;y++)for(let x=0;x<w;x++){const d=Math.hypot(x-40,y-40),yellow=center?d<8:d>16;data.set(d<22?(yellow?[255,220,0,255]:[245,245,245,255]):[20,100,30,255],(y*w+x)*4)}return data;}
test('center evidence measures position, not total yellow',()=>{const a=engine.extract(fixture(true),80,80).features,b=engine.extract(fixture(false),80,80).features;assert.ok(a.center_yellow>b.center_yellow);assert.ok(a.outer_yellow<b.outer_yellow)});
test('empty and uniform backgrounds cannot be accepted',()=>{for(const rgb of [[0,0,0],[245,245,245],[20,100,30]]){const data=new Uint8ClampedArray(80*80*4);for(let p=0;p<6400;p++)data.set([...rgb,255],p*4);const out=engine.analyze(data,80,80,profiles);assert.equal(out.decision.accepted,false);assert.equal(out.quality.usable,false)}});
test('all valid pixels belong to exactly one region',()=>{const out=engine.extract(fixture(),80,80);for(let p=0;p<6400;p++)assert.equal(out.masks.flower[p]+out.masks.leaf[p]+out.masks.context[p],1)});
test('rule data changes scores and missing measurements abstain',()=>{const p=[{id:'a',rules:{colour:[['yellow',.8,1,1]]}},{id:'b',rules:{colour:[['yellow',0,.1,1]]}}];assert.equal(engine.rank({yellow:.9},p)[0].id,'a');assert.equal(engine.rank({yellow:.01},p)[0].id,'b');assert.equal(engine.rank({},p)[0].observed_groups,0)});
test('catalog includes six Macau groups and seed-head hypothesis',()=>{for(const id of ['hibiscus','ixora','lantana','plumeria','bougainvillea','bidens'])assert.ok(profiles.some(p=>p.id===id));assert.ok(profiles.some(p=>p.stage==='mature_seed_head'));assert.equal(engine.analyze(fixture(),80,80,profiles).decision.accepted,false)});
test('guided extraction records a contained seed and structural uncertainty',()=>{const out=engine.extract(fixture(),80,80,{seed:{x:.5,y:.5}});assert.equal(out.quality.seeded,true);assert.equal(out.quality.seed_contained,true);for(const key of ['circularity','solidity','symmetry','visible_tips_low','visible_tips_high','tip_stability','centre_contrast'])assert.ok(Number.isFinite(out.features[key]),key);assert.ok(out.features.visible_tips_high>=out.features.visible_tips_low);assert.equal(typeof out.features.structural_class,'string')});
test('a tap outside detectable flower pixels fails explicitly',()=>{const out=engine.extract(fixture(),80,80,{seed:{x:0,y:0}});assert.equal(out.quality.usable,false);assert.equal(out.quality.seed_contained,false);assert.match(out.quality.issues.join(' '),/Tap did not land/)});
test('analysis stays uncalibrated and requests actionable follow-up',()=>{const out=engine.analyze(fixture(),80,80,profiles,{seed:{x:.5,y:.5}});assert.equal(out.decision.accepted,false);assert.ok(out.decision.follow_up.length>20);assert.equal(out.engine_version,'0.7.0')});
