const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={};vm.runInNewContext(fs.readFileSync('dist/floral-structure.js','utf8')+';this.observer=FloralStructure',context);const observer=context.observer;
function fixture({head=false,centreDots=false,petals=true,multiple=false}={}){const w=96,h=96,data=new Uint8ClampedArray(w*h*4),mask=new Uint8Array(w*h),centre=new Uint8Array(w*h),rays=new Uint8Array(w*h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const p=y*w+x,d=Math.hypot(x-48,y-48),a=Math.atan2(y-48,x-48),outer=d<38&&(petals||d<30);if(outer){mask[p]=1;const central=d<13;if(central)centre[p]=1;else rays[p]=1;const dot=centreDots&&central&&((x+y)%5<2);const rgb=central?(dot?[255,220,20]:[95,65,25]):[235,95+Math.round(Math.cos(a*6)*15),145];data.set([...rgb,255],p*4);}else data.set([20,90,30,255],p*4);}
 return{data,w,h,source:{masks:{flower:mask,centre,rays},head_structure:{status:head?'centre_surrounded_by_yellow_outer_region':'unknown'},quality:{usable:true},petals:{status:'stable_region_candidates',visible_region_count:6,shape:'broad'},morphology:{status:'exploratory',methods:[]}},context:{coarse:{quality:{issues:multiple?['Multiple similarly prominent regions']:[]}}}};}
test('central repetition alone never turns a lotus-like large flower into a composite head',()=>{const f=fixture({centreDots:true});const result=observer.analyze(f.data,f.w,f.h,f.source,f.context);assert.notEqual(result.value,'composite_head_candidate');assert.equal(result.value,'single_large_flower_candidate');});
test('disc repetition plus an outer ray proposal supports a composite-head candidate',()=>{const f=fixture({head:true,centreDots:true});const result=observer.analyze(f.data,f.w,f.h,f.source,f.context);assert.equal(result.value,'composite_head_candidate');assert.deepEqual([...result.evidence],['disc_like_centre_repetition','outer_ray_annulus']);});
test('multiple prominent targets force unresolved before structure naming',()=>{const f=fixture({head:true,centreDots:true,multiple:true});const result=observer.analyze(f.data,f.w,f.h,f.source,f.context);assert.equal(result.value,'unresolved');assert.match(result.reason,/Several similarly prominent targets/);});
test('the predeclared pilot is balanced and contains development images only',()=>{const pilot=JSON.parse(fs.readFileSync('tests/structure-experiment/manifest.json')),benchmark=JSON.parse(fs.readFileSync('dist/benchmark/manifest.json')),byId=new Map(benchmark.images.map(item=>[item.id,item]));assert.equal(pilot.images.length,16);for(const label of pilot.allowed_labels)assert.equal(pilot.images.filter(item=>item.structure_label===label).length,4,label);for(const item of pilot.images){assert.equal(item.split,'development');assert.equal(byId.get(item.id)?.split,'development',item.id);assert.ok(item.review_reason);}});
test('committed pilot report keeps abstentions in the denominator and passes declared gates',()=>{const report=JSON.parse(fs.readFileSync('tests/structure-experiment/evaluation.json'));assert.equal(report.reserved_images_loaded,0);assert.deepEqual(report.summary.positive_agreement,{agreed:11,total:12});assert.deepEqual(report.summary.hard_routing,{unresolved:4,total:4});assert.equal(report.summary.single_large_false_composites,0);assert.equal(report.summary.passed,true);});
