const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const context={};vm.runInNewContext(fs.readFileSync('dist/identification-v2.js','utf8')+';this.pipeline=IdentificationV2',context);const V=context.pipeline;
function proposal({coverage=.2,usable=true,multiple=false,edge=false}={}){const w=20,h=20,mask=new Uint8Array(w*h);for(let y=6;y<14;y++)for(let x=6;x<14;x++)mask[y*w+x]=1;if(edge)for(let y=0;y<15;y++)for(let x=0;x<15;x++)mask[y*w+x]=1;return{sample:{width:w,height:h},masks:{flower:mask},features:{flower_coverage:coverage},quality:{usable,proposal_count:multiple?3:1,issues:multiple?['Multiple similarly prominent regions']:[]}};}
function triage(){return{framing:{value:'usable',status:'observed'},flower_multiplicity:{value:'single_candidate',status:'observed'},head_grouping:{value:'unresolved',status:'unresolved'},leaf_visibility:{value:'no_reliable_blade',status:'unresolved'}};}
function candidate(id,score,extra={}){return{id,name:id,latin:id,stage:'flowering',taxonRank:'test',score,flower_score:score,coverage:1,observed_groups:4,missing_required:[],calibrationStatus:'validated',parts:{colour:1},...extra};}
function output(candidates,extra={}){return{quality:{usable:true},triage:triage(),thresholds:{minimum_score:.72,minimum_lead:.12},observations:{petalShape:{status:'region_candidate'},centre:{status:'unresolved'},arrangement:{status:'unresolved'}},decision:{follow_up:'Take another photo.'},candidates,...extra};}
test('triage keeps scale, multiplicity, head and leaf claims bounded',()=>{const normal=V.triage(proposal(),null,{status:'unknown'});assert.equal(normal.framing.value,'usable');assert.equal(normal.flower_multiplicity.value,'single_candidate');assert.equal(normal.head_grouping.value,'unresolved');assert.equal(normal.leaf_visibility.value,'no_reliable_blade');assert.equal(V.triage(proposal({coverage:.03}),null,{status:'unknown'}).framing.value,'wide_or_small');assert.equal(V.triage(proposal({coverage:.7}),null,{status:'unknown'}).framing.value,'tight_or_clipped');const multiple=V.triage(proposal({multiple:true}),{selectedId:2},{status:'centre_surrounded_by_yellow_outer_region'});assert.equal(multiple.flower_multiplicity.value,'multiple_candidates');assert.equal(multiple.head_grouping.value,'one_head_candidate');assert.equal(multiple.leaf_visibility.value,'blade_candidate_visible');});
test('a passing primary gate skips secondary evidence for the decision',()=>{const out=output([candidate('a',.9),candidate('b',.7)]);out.triage.leaf_visibility={value:'blade_candidate_visible',status:'region_candidate'};out.candidates[0].score=.88;const result=V.build(out);assert.equal(result.primary.gate.passed,true);assert.equal(result.secondary.ran,false);assert.equal(result.final.outcome,'identified');assert.deepEqual(result.final.candidates.map(c=>c.id),result.primary.candidates.map(c=>c.id));assert.equal(result.policy.automatic_acceptance_enabled,false);});
test('an unvalidated profile stays ambiguous even with a strong primary score and lead',()=>{const out=output([candidate('a',.95,{calibrationStatus:'experimental'}),candidate('b',.7)]),result=V.build(out);assert.equal(result.primary.gate.predicates.profile_validated,false);assert.equal(result.primary.gate.passed,false);assert.equal(result.secondary.ran,false);assert.equal(result.final.outcome,'ambiguous');});
test('eligible primary ambiguity invokes bounded secondary reranking',()=>{const out=output([candidate('a',.8,{score:.775}),candidate('b',.79)]);out.triage.leaf_visibility={value:'blade_candidate_visible',status:'region_candidate'};const result=V.build(out);assert.equal(result.primary.gate.passed,false);assert.equal(result.secondary.ran,true);assert.equal(result.final.candidates[0].id,'b');assert.equal(result.final.outcome,'ambiguous');const change=result.secondary.changes.find(c=>c.id==='a');assert.ok(Math.abs(change.adjustment+.025)<1e-9);});
test('secondary evidence cannot rescue tight, multiple or low-scoring primary evidence',()=>{for(const mutate of [out=>out.triage.framing.value='tight_or_clipped',out=>out.triage.flower_multiplicity.value='multiple_candidates',out=>out.candidates.forEach(candidate=>candidate.score=candidate.flower_score=.4)]){const out=output([candidate('a',.8),candidate('b',.79)]);out.triage.leaf_visibility={value:'blade_candidate_visible',status:'region_candidate'};mutate(out);assert.equal(V.build(out).secondary.ran,false);}});
test('poor input is ambiguous/not-assessable while a low usable fit can be no-match',()=>{const poor=output([candidate('a',.8),candidate('b',.6)]);poor.quality.usable=false;poor.triage.framing.value='unresolved';assert.equal(V.build(poor).final.internal_state,'not_assessable');assert.equal(V.build(poor).final.outcome,'ambiguous');const low=output([candidate('a',.3),candidate('b',.2)]);assert.equal(V.build(low).final.outcome,'no_match');});
test('v2 UI exposes all five stages and explicit experimental language',()=>{const html=fs.readFileSync('dist/identification-v2.html','utf8'),ui=fs.readFileSync('dist/identification-v2-ui.js','utf8');for(const stage of ['QUICK TRIAGE','PRIMARY EVIDENCE GATE','SECONDARY EVIDENCE','FINAL OUTCOME'])assert.match(html,new RegExp(stage));assert.match(html,/match strength is not probability/);assert.match(ui,/REVIEW REQUIRED/);});
