const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');const c={};vm.runInNewContext(fs.readFileSync('dist/leaf-engine.js','utf8')+';this.leaf=LeafEngine',c);const L=c.leaf;
function image(kind='oval',angle=0){const w=200,h=200,data=new Uint8Array(w*h*4);for(let y=0;y<h;y++)for(let x=0;x<w;x++){const dx=x-100,dy=y-100,u=dx*Math.cos(angle)+dy*Math.sin(angle),v=-dx*Math.sin(angle)+dy*Math.cos(angle),a=kind==='round'?25:45,b=kind==='narrow'?10:25,inside=u*u/(a*a)+v*v/(b*b)<1;data.set(inside?[45,140,65,255]:[60,60,60,255],(y*w+x)*4);}return {data,w,h};}
test('isolated leaf regions produce rotation-stable coarse shape and no invented anatomy',()=>{for(const [kind,expected] of [['oval','broad'],['round','round'],['narrow','narrow']])for(const angle of [0,.7]){const f=image(kind,angle),o=L.analyze(f.data,f.w,f.h);assert.equal(o.observations.shape,expected);assert.equal(o.observations.tip,null);assert.equal(o.observations.arrangement,null);assert.equal(o.association,'unverified');assert.ok(o.selectedId);}});
test('absent, large connected and flower-excluded regions abstain',()=>{const {data,w,h}=image();for(const mode of ['empty','green','excluded']){const d=data.slice();if(mode!=='excluded')for(let p=0;p<w*h;p++)d.set(mode==='green'?[40,140,60,255]:[50,50,50,255],p*4);const o=L.analyze(d,w,h,mode==='excluded'?new Uint8Array(w*h).fill(1):null);assert.equal(o.selectedId,null);assert.equal(o.observations.shape,null);}});
test('clipped and tiny blades cannot enter leaf rank',()=>{for(const pts of [[0,1,2,3],Array.from({length:300},(_,p)=>Math.floor(p/10)*100+p%10)]){const m=L.measure(pts,100,100);assert.equal(m.usable,false);assert.equal(m.observations.shape,null);}});
test('leaf masks stay inside pixels, exclude flower, and label selected candidate only',()=>{const f=image(),exclude=new Uint8Array(f.w*f.h);exclude[100*f.w+100]=1;const o=L.analyze(f.data,f.w,f.h,exclude);assert.equal(o.mask[100*f.w+100],0);for(let p=0;p<o.mask.length;p++)if(o.mask[p])assert.equal(o.labels[p],o.selectedId);});
test('unmapped reference alternatives and missing leaf remain neutral',()=>{const knowledge={plants:[{id:'a',sources:[],traits:{leafShape:{values:['oval','lobed'],sources:[]}}}]};assert.equal(L.rank({observations:{shape:'narrow'}},knowledge)[0].score,null);assert.equal(L.rank({observations:{shape:null}},knowledge)[0].score,null);assert.equal(L.rank({observations:{shape:'broad'}},knowledge)[0].score,1);});
test('nearby leaf can separate only flower near ties; no absent-leaf boost or acceptance',()=>{const out={quality:{usable:true},candidates:[{id:'a',score:1},{id:'b',score:.99},{id:'c',score:.8}],decision:{accepted:false}};const leaf={quality:1},r=[{id:'a',score:0},{id:'b',score:1},{id:'c',score:1}];const o=L.combine(out,leaf,r);assert.equal(o.candidates[0].id,'b');assert.equal(o.candidates.find(c=>c.id==='a').leaf_adjustment,-.025);assert.equal(o.candidates.find(c=>c.id==='c').score,.8);assert.equal(o.decision.accepted,false);const unchanged=L.combine(out,leaf,[]);assert.equal(unchanged.candidates[0].score,1);const clear=L.combine({...out,candidates:[{id:'a',score:1},{id:'b',score:.9}]},leaf,r);assert.equal(clear.candidates[0].id,'a');});
test('tapered endpoint is inspectable but never substituted for verified tip',()=>{const points=[];for(let y=40;y<160;y++)for(let x=50;x<150;x++){const half=y<100?(y-40)/2:30*Math.sqrt(1-((y-100)/60)**2);if(Math.abs(x-100)<half)points.push(y*200+x);}const m=L.measure(points,200,200);assert.equal(m.observations.tip,null);assert.equal(m.observations.base,null);assert.equal(m.observations.endShape,'pointed_end');});
